---
properties:
  key:
    description: "The key identifier of the icon.\n"
    enum:
    - "APP1"
    - "APP2"
    - "APP3"
    - "APP4"
    - "APP5"
    - "APP6"
    - "APP7"
    - "APP8"
    - "APP9"
    - "APP10"
    - "APP11"
    - "APP12"
    - "APP13"
    - "APP14"
    - "APP15"
    - "APP16"
    - "APP17"
    - "APP18"
    - "APP19"
    - "APP20"
    - "APP21"
    - "APP22"
    - "APP23"
    - "APP24"
    - "APP25"
    - "APP26"
    - "APP27"
    - "APP28"
    - "APP29"
    - "APP30"
    - "APP31"
    - "APP32"
    - "APP33"
    - "APP34"
    - "APP35"
    - "APP36"
    - "APP37"
    - "APP38"
    - "APP39"
    - "APP40"
    - "APP41"
    - "APP42"
    - "APP43"
    - "APP44"
    - "APP45"
    - "APP46"
    - "APP47"
    - "APP48"
    - "APP49"
    - "APP50"
    - "APP51"
    - "APP52"
    - "APP53"
    - "APP54"
    - "APP55"
    - "APP56"
    - "APP57"
    - "APP58"
    - "APP59"
    - "APP60"
    - "APP61"
    - "APP62"
    - "APP63"
    - "APP64"
    - "APP65"
    - "APP66"
    - "APP67"
    - "APP68"
    - "APP69"
    - "APP70"
    - "APP71"
    - "APP72"
    - "APP73"
    - "APP74"
    - "APP75"
    - "APP76"
    - "APP77"
    - "APP78"
    - "APP79"
    - "APP80"
    - "APP81"
    - "APP82"
    - "APP83"
    - "APP84"
    - "APP85"
    - "APP86"
    - "APP87"
    - "APP88"
    - "APP89"
    - "APP90"
    type: "string"
  type:
    description: "The icon type:\n- FILE: An uploaded image.\n- PRESET: A preset icon\
      \ within Kintone.\n"
    enum:
    - "FILE"
    - "PRESET"
    type: "string"
required:
- "type"
- "key"
type: "object"

